### ISSUE TITLE
[BUG] Singleplayer crash in modpack environment

### ISSUE THREAD

**Issue by CaveNJ** [tofodroid/mimi-mod#117]
**Description**

**To Reproduce**
1. Open a singleplayer world with some blocks in the world from 4.0.1
2. Crash... sometimes. It's weird. I've opened the world without issue once or twice, but the crash has happened a few times.

**Expected behavior**
... *not* crash :)

**Crash Log**
[crash-2024-03-27_23.29.56-server_MIMI.txt](https://github.com/tofodroid/mimi-mod/files/14783610/crash-2024-03-27_23.29.56-server_MIMI.txt)
[latest.log](https://github.com/tofodroid/mimi-mod/files/14783629/latest.log)

**Environment**
 - OS: Windows 10
 - Mod Version: 1.20.1-4.0.2
 - Minecraft Version: 1.20.1
 - Forge Version: 4.2.19

Note: I have this in a modpack with a lot of other stuff like TFC, Create, IE, ... but the crash log looks like it's just MIMI doing this.

**Comment by tofodroid** [comment]
Hello! Thanks for the bug report! Based on your description of the issue it sounds like there may be multiple different crashes occurring, but I think I see the root cause of the one in your latest crash log.

I'll get a new build out shortly that should resolve that specific issue and we'll see if that resolves all of the crashes or if you continue to run into other crashes.

Thanks again for the report!

**Comment by tofodroid** [comment]
I've just uploaded version 4.0.3 to CurseForge and Modrinth which should resolve this issue. All Modrinth versions and avaiable now and the CurseForge versions should be available soon, but some others are going through manual review by CurseForge which can take up to 24 hours.

Let me know if this new version resolves your issues!
