### ISSUE TITLE
[BUG] Autoplayer doesn’t work on all instruments

### ISSUE THREAD

**Issue by Yafffo** [tofodroid/mimi-mod#128]
**Describe the bug**

The autoplayer I use plays the song perfectly on the Piano instruments and the Bone Lute (strangely) but not anything else, such as the Saxophone, Trombone, drums, etc. It just highlights the keys like you played them, but no sound comes out.

**To Reproduce**
3. See error

Play the autoplayer on the piano
Works fine

Go to a different instrument
Doesn’t work

**Expected behavior**

It would auto play like it does on the piano.

**Screenshots**

**Crash Logs**
If applicable, add log files or crash reports that were generated.

**Environment (please complete the following information):**
 - OS: Win 11
 - Mod Version: [1.16.5 Release]
 - Minecraft Version: [ 1.16.5]
 - Forge Version: i’ll have to check later

**Additional context**

**Comment by tofodroid** [comment]
Hello! Thanks for the bug report! Unfortunately because the version of Minecraft is several years old and there is a low number of players compared to other versions the 1.16 version of the mod is no longer maintained.

If you are able I would highly suggest trying out a newer version of the mod on Minecraft 1.19 or later!
