### ISSUE TITLE
[IMPROVEMENT]

### ISSUE THREAD

**Issue by AngryAshley** [tofodroid/mimi-mod#129]
**Is your improvement request related to a problem? Please describe.**
Mimi now doesn't understand folders. I have folders in the folder where the midis are located, but Mimi doesn't read into them recursively.

**Describe the solution you'd like**
I'd like for folders to be included and usable in the midi select dialog.

**Additional context**
I used to have all my midis sorted in folders when i used 3.1.1, but our server has upgraded to mimi 4.0.8, and now it can't find my midis anymore.
I propose that the folders look something like this:  [foldername]  , to make it clear which items are folders. Perhaps simply adding an item that brings you to the folder above would be enough to make it all properly traversable. Watch out that you don't let users go outside of the top folder though!

**Comment by tofodroid** [comment]
Hello and thank you so much for the suggestion!

I have actually been working on bringing back the previous ability to change the folder that the Transmitter is looking for songs in and it will be included in the upcoming 4.1.0 release! 😊

I do also like the idea of being able to traverse folders within the Transmitter itself, so that's something that I will keep in mind as a future enhancement!

**Comment by tofodroid** [comment]
Version 4.1.0 has been release including this feature!
