### ISSUE TITLE
[FEATURE] Add an option to change to Virtual Piano Layout for instruments.

### ISSUE THREAD

**Issue by The-Weeb-Guy** [tofodroid/mimi-mod#13]
**Is your feature request related to a problem? Please describe.**
Right now MIMI uses its own layout, which doesn't have much written music for it, and its range is limited when you are playing via QWERTY keyboard.

**Describe the solution you'd like**
Use the layout from Virtual Piano as an toggleable option, and there is a lot of music written for it and has a larger playable range, allowing more options of what you can play without plugging in a MIDI device.

**Describe alternatives you've considered**
N/A

**Additional context**
https://virtualpiano.net/
![d9192c84796717cdd80d92059d679a7a](https://user-images.githubusercontent.com/59518595/124680003-805bf100-de93-11eb-8791-2bb81fec4ac6.png)

**Comment by tofodroid** [comment]
This is a great idea, thanks! The current system is definitely pretty clunky when you need to play above or below the visible note range and have to shift. 

One thing that's not currently documented is that you can shift the visible note range up and down using the arrow keys on your keyboard that correspond to the buttons on the GUI so that might help a little bit in the meantime! But I'll definitely look into adding this.

I'm not sure that I'll be able increase the number of visible notes by much but with the layout that you're proposing it's be possible to play notes that are not currently visible which is pretty cool!

Thanks again for the suggestion!

**Comment by tofodroid** [comment]
This has been added and will be available in 1.16.5-1.1.0! If I don't hear of any additional bugs or small tweaks I'll upload beta build of of this version to CurseForge on Friday! See #14 for more info

**Comment by tofodroid** [comment]
Beta released on CurseForge!
