### ISSUE TITLE
7GB Log File. [BUG]

### ISSUE THREAD

**Issue by Quest79** [tofodroid/mimi-mod#136]
**Describe the bug**
Log file is 7GB. This mod is pouring out just endless errors to it.

**To Reproduce**
1. Play the game
2. 2. Look at log file?

**Expected behavior**
Not a 7GB log file

**Screenshots**
https://i.imgur.com/udMlzqq.png

**Crash Logs**
Here is a snip unless you wnat 7GB log file lmao
https://pastebin.com/UvpZau5w

**Environment (please complete the following information):**
 - OS: Win11
 - Mod Version: mimimod-1.20.1-4.1.0.jar
 - Minecraft Version: 1.20.1
 - Forge Version: 47.2.18

**Additional context**
halp

**Comment by tofodroid** [comment]
Hello!

I took a quick look at the log file and it looks like something funky is going on with the sound device that Minecraft is trying to output its sound too. The first chunk of that log file is an error coming from Minecraft itself saying it could not connect to the selected audio output device. That error is what triggers the errors in MIMI since MIMI also tries to connect to the same output device as Minecraft to output note sounds.

After those first 140 lines there are a whole bunch of lines coming from the Minecolonies mod reporting issues with sounds from that mod, and then the whole thing repeats it self.

So the root of this issue appears to not actually MIMI but seems to be something with Minecraft itself connecting to your selected audio output device and causing MIMI and Minecolonies to both have issues. Whatever is causing that issue in Minecraft also seems to be repeating itself multiple times per second which explains how the log file is getting so large.

I would try selecting a different Audio Output device in Minecraft's setting
