### ISSUE TITLE
[BUG] Adding midi files does not work.

### ISSUE THREAD

**Issue by LordMrRat** [tofodroid/mimi-mod#139]
Even after I add midi files into the midi folder, it dosen't detect them in the transmitter
Mod version: 1.20.1-4.1.0-RELEASE-FORGE
Minecraft Version: 1.20.1
Forge Version: 47.2.20

Also trying to use it in a modpack.

**Comment by tofodroid** [comment]
Hello! Apologies for the slow reply, I was away from development for a couple months because I got married but hopping back into it now!

Have you tried restarting your game after adding the MIDI files to the folder? Sometimes MIMI struggles to detect new MIDI files until the game is restarted. It seems to be a randomly occurring issue that I can't reliably reproduce so it's hard to figure out what's causing it..
