### ISSUE TITLE
Game crash when backing out of instrument GUI

### ISSUE THREAD

**Issue by Scyriate** [tofodroid/mimi-mod#23]
I am not sure why but my game crashes whenever I activate midi channel 1 on an instrument and then try to back out of the GUI by pressing escape, doing so causes the game to freeze and stop responding before eventualy force saving the world and then closing the game, opening the launcher with the report of a crash.

This is what the launcher says: 
> The game crashed whilst keypressed event handler
> Error: java.lang.NullPointerException: keyPressed event handler
> Exit Code: -1

**Comment by tofodroid** [comment]
Hello! Thanks for reporting the issue. Do you know what version of the mod you are using? Also would you be able to attach your crash log file? 

You can find the crash log file location by doing this (assuming you're using CurseForge):

1. Open CurseForge and click on the profile that you have installed the mod to
2. Click on the three dots next to the "Play" button in the top right and click on "Open Folder"
3. Within the opened folder open the crash-logs folder (if it exists) and attach the latest log file from there, otherwise open the logs folder and attach the "latest.log" file that should be in there.

I'll start taking a look at this later today but if you could provide any of the additional info above that would help me narrow down the issue and hopefully resolve it faster. Thanks again for reporting this!
