### ISSUE TITLE
[IMPROVEMENT] New models for some instruments

### ISSUE THREAD

**Issue by SubCitri** [tofodroid/mimi-mod#25]
**Is your improvement request related to a problem? Please describe.**
While the piano is mechanically probably one of the best instruments in the mod, its model seems to be rather small in comparison to what you usually think of when you think of a piano, being slightly smaller than a stair block but slightly taller than a slab. The same issue applies to the drums

**Describe the solution you'd like**
Perhaps redoing the model, Making it multiblock and slightly larger for both like a bed in a way. Modeling the piano after the grand piano with it being like 3x2 or having a western saloon piano with it being 3x2 and probably easier to model with tabula.

**Additional context**

**Comment by tofodroid** [comment]
Thanks for the suggestion! The art is definitely the weak point of the mod right now haha. Unfortunately I don't really have any art skills whatsoever and currently don't have the free time to try and acquire any but if you or anyone else is interested in contributing I would be all for that!

I will at least take a look into scaling the current block instrument models out beyond 1x1 because I agree that they're too small right now. That's something I should be able to figure out! 

Thanks for the suggestion, I really appreciate it and any feedback on the mod!

**Comment by tofodroid** [comment]
Related: https://github.com/tofodroid/mimi-mod/issues/123
