### ISSUE TITLE
why use midi device's voice smaller than computer keyboard

### ISSUE THREAD

**Issue by aich1226** [tofodroid/mimi-mod#41]
why use midi device's voice smaller than computer keyboard

**Comment by tofodroid** [comment]
Hello, thanks for the question!

I'm not entirely sure what you're asking but I'll try to answer and if it doesn't make sense feel free to reply again and hopefully I can provide the answer you're looking for!

The most straight-forward way to play instruments in MIMI is to use the Computer Keyboard as you said, but if you use a physical MIDI device like a real midi-equipped piano then you can play every note that's available on the piano which is many more keys than a computer keyboard. The VPiano keyboard layout in MIMI lets you play 6 full octaves which should be enough for pretty much any song but in order to allow every key on a real physical midi device to function MIMI has to support everything.

There are also some fancy MIDI files out there that use extremely low and high notes for some of the MIDI sound-effect voices like the Dog Bark and Bird Chirp to create different effects. While MIMI doesn't support those voices yet I'm hoping to eventually support most (or maybe all) MIDI voices so I would want to make sure every possible MIDI file can be properly played in MIMI.

I am considering adding a feature later to enable a simplified piano view in MIMI that only shows one or two octaves primarily for use in adventure maps but also just to clean up the view a bit for simpler songs.

Hopefully that makes sense!
