### ISSUE TITLE
[QUESTION] Cannot open gui?

### ISSUE THREAD

**Issue by superjaja05** [tofodroid/mimi-mod#44]
**Question**
Hey so uh i'm trying this mod for the first time, and i'm unable to open any instrument GUI? am i doing something wrong? i tried with held instrument , and instrument where you sit, none worked

also is there a discord? could be easier for quick help lol

**Environment (if applicable):**
 - OS: Win 10
 - Mod Version: 1.1.0
 - Minecraft Version: 1.16.5
 - Forge Version: 1.16.5 36.2.4

**Comment by tofodroid** [comment]
Hello! Thanks for reporting this issue and sorry to hear that it isn't working!

Re: Discord - Right now there isn't one because the community around MIMI hasn't really been big enough to warrant it, but it is something I've thought about doing as the mod grows!

I'm not sure off the top of my head why the GUIs wouldn't be opening for you but I'm certainly happy to try and help figure out why! First off, are you running any other mods along with MIMI (and Patchouli which MIMI uses)? I haven't tested the mod with a lot of others so there could be a conflict that I'm not aware of.

Another question: Are you playing in Single player, multiplayer, or LAN?

Another thing to try: There are actually a couple of ways to open the instrument GUI in MIMI. The usual way is what it sounds like you're trying where you either hold the instrument and right click or sit at the instrument and right click it again. The alternative way is to use the hotkeys when holding or sitting at an instrument (they're mostly there to make it easier to open a specific instrument when you're playing several at the same time). If you open up your controls menu in Minecraft you should be able to find the MIMI hotkeys and see what they're currently bound to. If you could try opening the instrument that way and let me know what happens I'd appreciate it!

Thanks again for reporting the issue and hopefully we can get to the bottom of it!

**Comment by superjaja05** [comment]
Hello! So yeah i do run MIMI with a ~100 mods modpack , with Patchouli
Second, i'm playing on multiplayer
and for the 3rd part , i've tried to sit and right click , and i tried to use the hotkeys, none worked

**Comment by tofodroid** [comment]
Gotcha, thanks for the information!

Is the modpack you're playing on one that's available on CurseForge or somewhere else or is it a custom one? I'm wondering if there's a way to get a mod list so I can take a peek and see if there are any that stand out as potentially causing a conflict.

Since you're playing on Multiplayer would you be able to hop into a Singleplayer world and see if the issues are present there as well? If you do see the issue there as well if you could then close the game and attach the `latest.log` file to that's in your `logs` folder would be great! Let me know if you need help finding the log file and I can help you get to it.

Thanks!

**Comment by superjaja05** [comment]
Hey, yeah my modpack is a custom one, so its not available on CurseForge
Also i'm not sure what happened , but it seems to work on both SP and MP now? i haven't changed my mods or anything, so not totally sure why it happened lol, well thanks for helping!

**Comment by superjaja05** [comment]
Oh i forgot to ask though , i have a very long delay when i press a note manually , is that normal? and if it is, is there a way to lower the delay/disable it?

**Comment by tofodroid** [comment]
Haha magical solutions are always the best kinds of solutions! But glad it's working now and let me know if you run into problems again!


Re: Long delay when pressing notes - Hmm that's not expected, it should be pretty fast. There are some mod config settings you can change in the config file to reduce the delay but it should already be less than half a second so if your delay is longer than that I'm not sure it'll help...

Would you be able to check and see if you have that same delay both in SP and MP? Another user reported a similar issue a few months ago but I haven't heard back from them so not sure if they gave up or if it went away.

Under the hood MIMI uses Java's midi synthesizer to create sounds and bypasses the Minecraft sound engine so it's possible that the midi synth performance might be poor on certain systems for some reason..

**Comment by superjaja05** [comment]
Yeah i had the same delay in SP and MP , like 3 to 5s delay , maybe more

**Comment by tofodroid** [comment]
Hmm yeah that's definitely not expected.. 

Sounds in MIMI are generated by Gervill which is the MIDI Synthesizer that ships with Java and its performance is pretty dependent on your system. Within the context of Minecraft we don't get a lot of control over Gervill but there are a few settings that we have access to which can be tweaked in the MIMI config file (<Minecraft Directory>/config/mimi-client.toml) under the "MIDI Synth" category so you might be able to improve your latency by tweaking those. You should be able to change the config file while the game is running and when you save the file the changes should be applied immediately without needing to restart your game.

Some settings to look at:

**synthBaselineLatency**: This is the base latency of the Gervill synthesizer in milliseconds and it is used to allow the synthesizer to buffer notes before playing them. The default value is 250ms so changing that to something smaller should make a difference, but note that as the value approaches the minimum (10ms) the buffer length of Gervill decreases so you may notice stuttering in the sound.

**synthBitRate**: This is the data rate that should be used to generate the sound from the synthesizer. Higher values produce higher quality sound at the cost of more required processing power and possible latency, while lower values should require less processing power and have lower latency but may not sound quite as nice. I'd try lowering this to 8.

**synthSampleRate**: This is similar to the above and relates to how much processing power is spent generating higher quality sounds for each note. Higher values result in a higher quality sound, while lower values are a lower quality sound.

**synthJitterCorrection** : This is a feature of Gervill that makes note timing for accurate for MIDI files. It makes small adjustments to the time that the note is played based on your system time to reduce jitter (notes being off by a few milliseconds because of network latency and other factors). This feature does require a fair amount of processing power and does add a fair amount of latency as well so I'd recommend trying to disable this. Just note that if it is disabled you may notice some small timing errors with notes played from a MIDI file (hopefully nothing too noticeable though).

Let me know if tweaking any of those settings helps things! I don't have a lot of different hardware to test the mod out on so it's definitely very helpful to hear about issues like this that I can't recreate myself and I really appreciate the report!
