### ISSUE TITLE
[IMPROVEMENT] Additional Instruments :)!

### ISSUE THREAD

**Issue by majorcyto** [tofodroid/mimi-mod#45]
Hi,

Me and my friends are loving this mod! It works great for us and he haven't had any issues. We were hoping these instruments could be considered to be added? :)!

Cello
Tuba
Vibraphone
Glockenspiel
Steel Drums

These should be default instruments available in the midi library so they would only need an instrument model I suppose!

PS - Have you considered on adding a way for us to add our own instruments via a data pack or resource pack or something so we can just link to more instrument id's in the soundfont!

**Comment by tofodroid** [comment]
Hello! Glad to hear you're enjoying the mod and that it's working well for you and thanks for the suggestion!

I have been planning a percussion focused instrument update as the next one and a few of your suggestions fit right in so I'll definitely consider adding those as part of it!

I actually had a Tuba in the mod at one point but the sound (at least with the default soundfont on my system) was surprisingly similar to the Trumpet so I replaced it with the French Horn. The cello is in a similar boat where it sounded pretty similar to the violin on my system so i didn't prioritize it. But both of these are definitely instruments that I'll consider adding in future updates because I'm sure the sounds differ more significantly in other registers than the one I was testing with. 

If you're interested in adding them sooner I have considered creating a tutorial on adding instruments to MIMI because you're totally right that it mostly just requires a texture and a model for instruments that are placed as blocks! I think adding instruments could be a fun way for the community to get involved with MIMI!

Regarding your last suggestion - That's a really interesting idea! I think I already have the code for instruments generalized enough where that should be possible. I am going to look into doing that, it sounds like a really neat idea! I'll probably move that over to a new issue to track it separately. If you'd like to open it feel free; Otherwise I'll do so later this week!

Thanks again for all of the suggestions!

**Comment by tofodroid** [comment]
Just to give an update on this: I've added the Glockenspiel, Vibraphone, and Steel Drums in the latest update along with custom instrument support ([example](https://github.com/tofodroid/mimi-mod/tree/main/example))! A Beta Release is now up on Curseforge!

**Comment by tofodroid** [comment]
Hello again! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I've just released Beta versions for a major 4.0.0 update which adds the Cello and Tuba!

Please let me know if you have any other suggestions and thanks for these!
