### ISSUE TITLE
[BUG] Crash occurs when moving between two sources of music

### ISSUE THREAD

**Issue by Thresh90** [tofodroid/mimi-mod#57]
So I wanted to test if the music could be technically repeated if linked to the same transmitter, just far apart from one another
(Since there was no config on increasing the radius at which the music plays in)

To reproduce this error is quite simple
1.Make 2 4x4 points with Maestros and instruments inside one another
2. Move between the two sources
3.Crash

My guess is that something within the mod doesnt know how to handle multiple sources of a midi or something 

My provided crash log (I also tested this with just the mod itself and it still occurs
https://paste.ee/p/5owJA

**Comment by tofodroid** [comment]
Wow that's a very unique setup! Thanks so much for the bug report! I don't think I ever would've found this one in my own testing haha.

Also as far as having a configurable sound radius - that's a very good ode

**Comment by tofodroid** [comment]
Whoops - clicked the wrong button when submitting my comment. 😅

**Comment by Thresh90** [comment]
This same type of crash also occurs when putting multiple instruments in the same channel, not sure if it's cause of how many instruments can be played at a time or if it's just a slip up

**Comment by tofodroid** [comment]
I found the problem! There's supposed to be a limit of 15 instruments playing at the same time (client-side) but I accidentally had one of the checks set to 16 instead of 15 so it was trying to play one more instrument than it actually could. I'm hoping to find time to rewrite the client-side MIDI handling to support more than 15 instruments but it's not super high on my priority list right now. Fix will be pushed up soon!

Thanks again for the bug report and feature suggestion about the configurable radius!

**Comment by Thresh90** [comment]
No problem!

**Comment by Thresh90** [comment]
misclick

**Comment by tofodroid** [comment]
Versions with this bug fix are now up on CurseForge!

1.16.x: https://www.curseforge.com/minecraft/mc-mods/mimi-mod/files/3590400
1.18.x: https://www.curseforge.com/minecraft/mc-mods/mimi-mod/files/3590397

Thanks again for the report!
