### ISSUE TITLE
[FEATURE] Server Side Jukebox

### ISSUE THREAD

**Issue by majorcyto** [tofodroid/mimi-mod#58]
**Is your feature request related to a problem? Please describe. **
It would be pretty cool if we could have a Jukebox block (kind of like the conductor really) that syncs to receivers. The main difference is that the Midi files are being read from a server folder so that way someone can run up to the jukebox at any time and play a song which will play to the connected receivers.

That way even if someone doesn't have their own midi's downloaded at that moment they can hear some music. 

Also useful for playing a repeating playlist of songs in spawn for example or some other RP type situation.

**Describe the solution you'd like**
A Midi folder on the server that can be linked to a Jukebox block (or an option on the conductor block) that is linked to receivers to play music in a playlist without a player needing to hold the transmitter specifically.

**Describe alternatives you've considered**
I can't think of another way to do this without just having a player account afk in game lol

**Additional context**
Maybe as an optional feature we could allow midi files saving to the server that comes from a player client but this is kind of out of scope for this specific request and would add a lot of additional work.

**Comment by tofodroid** [comment]
Thanks for the suggestion! I'm glad you brought this idea up! I had previously considered doing something like this but at the time I wasn't sure that the version of Java installed on servers (since it can vary quite a bit and a specific version of Java isn't bundled with the server like it is with the Minecraft client) would be guaranteed to include the required implementations of various MIDI functionality. However now on version 1.18+ I include all of the MIDI implementations that I need (because Java 17+ doesn't easily let you access the bundled MIDI implementations anymore) so that shouldn't be a problem. 

I will definitely look into this!

**Comment by tofodroid** [comment]
This feature will be available in the next update, 3.0.0, releasing tomorrow!

**Comment by tofodroid** [comment]
Closed by #71
