### ISSUE TITLE
[BUG] MIMI (mimi) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by InstSnipe** [tofodroid/mimi-mod#60]
**Describe the bug**
I have no idea how it happened

**To Reproduce**
I also dont know how to reproduce it, asides from im on a mac

**Crash Logs**
https://pastebin.com/af6GrS23

**Environment:**
 - OS: MacOS High Sierra
 - Mod Version: 1.16.5-1.3.1
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.23

**Comment by tofodroid** [comment]
Hello! Thanks for reporting this issue!

I don't own a Mac or know too much about them but I think I see the issue! So typically on Windows Minecraft 1.16 runs using a specific version of Java that is included with the Minecraft installation and in Minecraft 1.16 that is supposed to be Java 8 (https://minecraft.fandom.com/wiki/Tutorials/Update_Java). Going by the logs that you posted it looks like your Minecraft is running on Java 16 (see line 28 in your log file). Starting in Java 16 a bunch of the internal Java functionality that MIMI uses became non-publicly-accessible which is why you're seeing this error. 

Minecraft 1.18 updated the included Java version to Java 17 so MIMI for Minecraft 1.18 had to be significantly modified in order for it to work on Java 17 and later because of this exact error you're seeing here. So the only real way I could fix this for the 1.16 version of MIMI would be to try to backport those fixes from the 1.18 version of the mod to the 1.16 version. I can look into that but it may take me a fair bit of time unfortunately because it's a lot of changes.

In the meantime I can think of a few options:

1. If you did explicitly change the version of Java that your Minecraft is using from 8 to 16 you could try changing it back to 8. 

2. If you didn't change anything about the version of Java that your Minecraft is using then you could try installing Java 8 and then explicitly telling Minecraft to use that version.

3. I'm not sure if you're running MIMI in a modpack or on its own but if you could try running Minecraft 1.18 instead with the 1.18 version of MIMI which should not have this issue.

Hopefully this helps! Let me know if you have any questions!
