### ISSUE TITLE
[QUESTION] Is this mod good?

### ISSUE THREAD

**Issue by twome** [tofodroid/mimi-mod#62]
**Question**
Is this mod good?

**Answer**
Yes, it is.

**In addition**
Rest in peace Dave Smith, inventor of the MIDI protocol, designer of the Prophet line of synthesizers, and important member of the hugely influential Sequential Circuits / Dave Smith Instruments synth companies, who passed away about a week ago. The modern Prophets still sound utterly gorgeous.

**Comment by twome** [comment]
Rust's instrument implementation is a stroke of genius I'm astonished no other dev had taken as inspiration (until now). Also, mandatory request for a Fabric/Quilt version (reading/writing Java makes me physically ill but I'm strongly considering exploring Scala and making a from-scratch Fabric adaptation of this mod, given your permission). Imagine the potential interactions with Sound Physics, Plasmo Voice, etc!

**Comment by tofodroid** [comment]
Thanks for the kind words about the mod! Sad to hear about Dave's passing, I hadn't heard about that; Maybe I can sneak a little tribute to him into the mod somewhere.. 🙂

Re: Fabric/Quilt - I have been considering porting the mod to [Architectury](https://github.com/architectury/architectury-api) to support other mod loaders but work has been kicking my butt lately and I haven't been able to find the time. Feel free to look into adapting the mod in Scala if you'd like, though I'd strongly suggest not using my code as a basis from which to learn Minecraft modding haha.

Interactions with other sound mods would be a challenge to implement because MIMI doesn't use the standard Minecraft sound system or OpenAL at all, it just uses the Java MIDI Synthesizer Gervill which uses Java.Sound stuff under the hood I believe. When I was first developing the mod I poked around a bit at piping the output from the MIDI Synth into the Minecraft sound system but didn't have much success there. I'm sure it's possible but I haven't spent much time looking into it.
