### ISSUE TITLE
[FEATURE] Player-less Transmitter

### ISSUE THREAD

**Issue by Rylan523** [tofodroid/mimi-mod#64]
**Is your feature request related to a problem? Please describe.**
From what I can tell a player must have a transmitter in their inventory in order to play midi as instruments require a switchboard to play midi.

**Describe the solution you'd like**
Some block or other feature that would allow a transmitter to broadcast a song without the need for an player to hold the transmitter; the transmitter could maybe be placed in a "broadcaster" block.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tofodroid** [comment]
Hello and thanks for the feature suggestion! You are correct that in order to play MIDI files from your computer you need to have a transmitter in your inventory. You can play the instruments manually without a transmitter but the transmitter must be in your hand or on your hotbar to play songs.

This idea sounds similar to https://github.com/tofodroid/mimi-mod/issues/58 but I think your idea would be to have it still play files from your computer rather than files that are uploaded to the server. I have a potential idea for how to implement https://github.com/tofodroid/mimi-mod/issues/58 and I think it would solve this request as well. I've got a start on the feature but it's not ready to go yet; hopefully I'll have an alpha version of it up in the next couple of weeks though!

**Comment by tofodroid** [comment]
Right now new features are only being released for the 1.19.x version of the mod. I unfortunately just don't have time right now to keep all of the versions in feature-parity and the code is now pretty significantly different in 1.19.x than in 1.16.x. Sorry!

**Comment by tofodroid** [comment]
This feature will be available in the next update, 3.0.0, releasing tomorrow!

**Comment by tofodroid** [comment]
Closed by #71
